### ISSUE TITLE
No colors for the buffers' labels with vim7.4

### ISSUE THREAD

**Issue by bliof** [fholgado/minibufexpl.vim#103]
I've just build the last version of vim under linux and pulled the master branch of the plugin and when I open 2 or more files the labels of the buffers stay the same.

**Comment by weynhamz** [comment]
@bliof Sorry for not relying, so, what's the status? Have you fixed this?

**Comment by bliof** [comment]
For some reason I had in a  little script of mine `au BufEnter * silent :syntax on` which was causing the problem. And when I was doing the test few month back on clean vim without plugins I think that I missed to add `syntax on` to the vimrc.

P.s. I noticed that when you create a session with `:mksession tmp.vim` and then opened it  `vim -S tmp.vim` the buffers won't be displayed on the top. You'll will have to move (:bp, :bn, ...) and then they will be shown. (https://github.com/fholgado/minibufexpl.vim/issues/113)
