### ISSUE TITLE
MiniBufExplCycleArround not working

### ISSUE THREAD

**Issue by deanmorin** [fholgado/minibufexpl.vim#107]
The `MiniBufExplCycleArround` option isn't working for me. I have the following settings in my vimrc:

```
let g:MiniBufExplCycleArround = 1
nnoremap H :MBEbp<cr>
nnoremap L :MBEbn<cr>
nnoremap ˙ :MBEbb<cr>
nnoremap ¬ :MBEbf<cr>
```

When I get to the last buffer:

`:MBEbn` -> `You have reached the last buffer!`
`:MBEbf` -> `You have reached the most recent buffer!`

Also, `Arround` should be spelled `Around` (this was my first problem when trying to use this option).

Thanks for the great plugin!

**Comment by chrisvanpatten** [comment]
Just encountered this as well. Would be great to get a fix.

**Comment by sukeyisme** [comment]
let g:MiniBufExplCycleArround = 1    the word Mini should be mini

**Comment by deanmorin** [comment]
@sukeyisme Huh, thanks!
