### ISSUE TITLE
moving tabline to top of vim? 

### ISSUE THREAD

**Issue by dmix** [fholgado/minibufexpl.vim#116]
I noticed in the screenshots that the buffer list is at the top of VIM. I'm trying to move mine from below the statusbar to the top.

It looks like you are using mvim, but is it possible to do this in terminal gvim on linux?

I've been searching everywhere and couldnt find a solution.

**Comment by weynhamz** [comment]
It should be on the top by default. Do you have 'splitbelow' set somewhere, if so, you need to explicitly have 'let g:miniBufExplBRSplit = 0' in you vimrc, because the default value of that option is read from 'splitbelow'.

**Comment by dmix** [comment]
oh right I did have splitbelow set. Thanks that worked.
