### ISSUE TITLE
MBE always on top

### ISSUE THREAD

**Issue by djornada** [fholgado/minibufexpl.vim#123]
if user setted splitbelow
MBE is showed at the bottom

**Comment by janhh** [comment]
Hi. I had the same problem. Looking around I found this.

let g:miniBufExplBRSplit = 0

It's explained in the help text, :h g:miniBufExplBRSplit.
I didn't fully understand the help text at first, but I got it when I browsed the source in github repository.

**Comment by djornada** [comment]
Ok!
Thanks
