### ISSUE TITLE
calling :syntax enable forces MBE to loose coloring

### ISSUE THREAD

**Issue by skupr** [fholgado/minibufexpl.vim#124]
I am editing and reloading vimrc quite often, and when I reload it, MBE looses all coloring.
I've figured out that this is because of string
:syntax enable
Could you please fix that or tell some workaround for my vimrc?

**Comment by skupr** [comment]
Found workaround:
in .vimrc:

``` vim
"Fix MBE syntax if coloring lost
function! MBESyntaxReset()
  syn clear
  syn match MBENormal                   '\[[^\]]*\]'
  syn match MBEChanged                  '\[[^\]]*\]+'
  syn match MBEVisibleNormal            '\[[^\]]*\]\*'
  syn match MBEVisibleChanged           '\[[^\]]*\]\*+'
  syn match MBEVisibleActiveNormal      '\[[^\]]*\]\*!'
  syn match MBEVisibleActiveChanged     '\[[^\]]*\]\*+!'
endfunction
command! MBESyntaxReset call MBESyntaxReset()
function! MBEFixAfterSyntaxEnable()
  if exists(":MBEFocus") " do job ony if MBE already loaded
    MBEFocus
    MBESyntaxReset
    wincmd w
  endif
endfunction
command! MBEFixAfterSyntaxEnable call MBEFixAfterSyntaxEnable()
```

and then,

``` vim
syntax enable
MBEFixAfterSyntaxEnable
```

note that it goes AFTER syntax enable string.

It's a bit complex, and probably there may be easier solution, but it works for me transparently.

**Comment by Fuzzier** [comment]
Create a syntax file: "minibufexpl.vim" under "minibufexpl.vim\syntax\".
Put the following content into the syntax file:

```
  syn match MBENormal                   '\[[^\]]*\]'
  syn match MBEChanged                  '\[[^\]]*\]+'
  syn match MBEVisibleNormal            '\[[^\]]*\]\*'
  syn match MBEVisibleChanged           '\[[^\]]*\]\*+'
  syn match MBEVisibleActiveNormal      '\[[^\]]*\]\*!'
  syn match MBEVisibleActiveChanged     '\[[^\]]*\]\*+!'
```

**Comment by ryanartecona** [comment]
+1, just ran into this today. Not a huge pain, but it would be nice to not need to restart vim after changing some settings & reloading ~/.vimrc (and more importantly, to not have to remember this particular caveat).
