### ISSUE TITLE
MBE breaks command history (q:) and search history (q/ and q?)

### ISSUE THREAD

**Issue by ghost** [fholgado/minibufexpl.vim#15]
MBE 6.4.0
Vim 7.3.189
Ubuntu 10.04

Vim open, no files loaded, no interference.
Vim open, one or more files loaded, I get the following error on entry into the command history, and with every single keystroke while in the command history (and search histories).

Error detected while processing function <SNR>19_AutoUpdate..<SNR>19_StartExplorer..<SNR>19_FindCreateWindow:
line   20:
E11: Invalid in command-line window; <CR> executes, CTRL-C quits: 1 wincmd w

**Comment by huyz** [comment]
I ran into the same issue.

**Comment by fholgado** [comment]
Hi guys,

I am not seeing this issue. Please try and update to the latest version of the plugin. I just updated the stable branch with the latest changes.

Please let me know if you are still experiencing this, if not, let's go ahead and close this one out.

Thanks :)

**Comment by huyz** [comment]
It seems to be fixed for me.
