### ISSUE TITLE
Window movement commands don't work

### ISSUE THREAD

**Issue by lamnk** [fholgado/minibufexpl.vim#16]
I have set `let g:miniBufExplMapWindowNavVim = 1` in my .vimrc but they don't work. Used on MacVim 7.3

**Comment by fholgado** [comment]
Hi there. Thanks for letting me know! I'll take a look and see what could be wrong. In the meantime, I actually have this in my .vimrc which should do the same:

```

" Smart way to move btw. windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
```

**Comment by fholgado** [comment]
This seems to work OK for me. Closing the issue for now unless anyone else reports this not working.
