### ISSUE TITLE
rotate windows shouldn't move mbe

### ISSUE THREAD

**Issue by moopet** [fholgado/minibufexpl.vim#18]
Resizing windows doesn't affect the mbe window - it stays minimum height at the top of the screen, which is great. However, rotating windows with <c-w>r moves it away from the edge. It should stay fixed - probably by hiding it before a window rotation and then re-showing it afterwards.

**Comment by fholgado** [comment]
Thanks for reporting this. Already have it noted for a fix!

**Comment by fholgado** [comment]
I believe this is fixed now, can you verify?
