### ISSUE TITLE
Closing sidebar MBE in gVim exposes a redraw glitch

### ISSUE THREAD

**Issue by ssokolow** [fholgado/minibufexpl.vim#2]
When closing a MiniBufExplorer sidebar using either `\mbt` or `g:miniBufExplCloseOnSelect = 1`, usually (but not always), only some of the rows will get redrawn.

I've tested it on gVim 7.3.50 on Gentoo Linux with MBE c80473ed3990e3a2c4723d0d9f7d902511180423 (6.4.1 by the ChangeLog, 6.4.0 by the version string).  but I first noticed the problem with Oliver's 6.3.4 off VimScripts.

The number or rows involved varies and sometimes they're at the top while other times they're at the bottom, but they appear to always be in a single block, so my guess is that it's some kind of race condition analogous to tearing in a GUI without vsync.

I know MBE can't fix gVim bugs, but if there's some way to force a redraw sufficiently late after closing the split, that might be a workaround worth implementing.

Here are some screenshots to illustrate the problem:
- [After selecting a different buffer](http://img828.imageshack.us/img828/9813/20110108202924674x484sc.png)
- [After selecting a different buffer and a brief hold on the down arrow](http://img46.imageshack.us/img46/4031/20110108202952674x469sc.png)

**Comment by fholgado** [comment]
Stephan,

I've noticed this as well, but in my case (using MacVim), I get errors that look like the colors are off sometimes, and of course, I can't get it to happen right this moment.

I know there is some code in MBE that deals with the refresh, so I will take a look and see what I can find. This one actually irks me quite a bit, I definitely want to get it cleaned up!

Thanks again, and I'll keep you posted!

**Comment by fholgado** [comment]
Stephan,

I am looking into this issue, but again, I can't seem to reproduce anything like what you've shown me here on my machine running MacVim. The only thing that I do see that _might_ be related is what I believe to be a bug in the regex that handles the highlighting for each buffer tab. You can see it here:

http://fhl.gd/W4ge

If I'm interpreting your screenshot correctly, I am assuming the characters in red (t,t,w,f) are out of whack and the highlighting in green is also wrong.

I don't have access to a Gentoo box to test in, so I will rely on you to continue with this. I will take a much closer look later tonight at the function that draws the text on the screen to see if there is anything there that might cause problems.

Let me know if you find out anything else.

**Comment by ssokolow** [comment]
Basically, all the rows which still show the MBE sidebar haven't been redrawn at all but gVim thinks they have, so the (t,t,f,w) are the first characters of the actual content of those lines. (The buffer selected is setup.cfg but the lines which retain leftover MBE visuals are still showing setup.py)

I'm assuming the bits like `[easy_install]` got drawn in full because of the cursor movements necessary to draw the paired bracket highlights when I passed through them.

As for why MacVim isn't showing the issue, I suspect it's specific to gVim. I couldn't duplicate the problem in the standard ncurses console Vim inside Yakuake and I bet you wouldn't be able to duplicate it with console vim running inside Terminal.app either.

I have a bad history when it comes to keeping promises in a timely fashion (though I always keep them eventually) but I'll try to find time to find a LiveCD or disk image which demonstrates the problem so you can easily test in VirtualBox.

**Comment by ssokolow** [comment]
I haven't had time to find a VM image for you, but I did write a workaround which seems to solve the problem on gVim and shouldn't run on other UIs.

Assuming I don't screw up the cURL command, this should be followed by a pull request after a minute or two.

**Comment by ssokolow** [comment]
Bah. The GitHub API is being obtuse. I'll just create a new pull request with its own issue.

**Comment by ssokolow** [comment]
Hmm. Just noticed that it doesn't solve the problem completely. What it does do is make it a bit less likely and, when it does happen, causes vim to display a block of whitespace where, previously, it would display text from a buffer not currently selected.

**Comment by fholgado** [comment]
Stephan,

Thanks so much for taking the time to look at the fixes! I have been away for a hockey tournament this weekend but I will get the changes merged in here shortly. It seems like you are on the right track fixing the issue. I'll leave it open until it's fully resolved.

Thanks again!
Federico
