### ISSUE TITLE
Can't navigate with Control-H & Control-L

### ISSUE THREAD

**Issue by jackfranklin** [fholgado/minibufexpl.vim#25]
Hey, 

In my .vimrc I have the following lines:

```
" Smart way to move btw. windows 
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

let g:miniBufExplMapWindowNavVim = 1
```

Control+J or Control+K works fine to move up/down but can't go left or right.

Any ideas really appreciated.

Thanks.

**Comment by fholgado** [comment]
Hm. MBE attempts to do the same thing that you've got in your .vimrc, and you're turning on that setting right below the duplicate map. You might want to either let MBE do it and remove the mappings from your .vimrc, or tell MBE NOT to map those keys and use the code that you currently have in your .vimrc.

Make sense?
