### ISSUE TITLE
Breaks FuzzyFinder opening files

### ISSUE THREAD

**Issue by andrew-hill** [fholgado/minibufexpl.vim#3]
Having trouble tracking down exactly what's causing the problem, but these are the symptoms...

I'm using the FuzzyFinder plugin as well: http://www.vim.org/scripts/script.php?script_id=1984
And I'm having a weird interaction between this and MBE.

In previous versions of MBE (from vim.org, including MBE++) FuzzyFinder would open files in the window that's currently open, and the filename would appear in the MBE window as expected, exactly as if you'd typed :e filename.

Since upgrading to minibufexpl from this git repo, I've found that opening a file with FuzzyFinder will cause a new split window to open, but it's always only a single row high and at the top of the windows (immediately below the MBE window). Even if the file is already open in a buffer, opening it with FuzzyFinder (e.g. via the "open a buffer" FufBuffer command) will make a new split window at the top, a single row high.

If I disable MBE, FuzzyFinder works fine and if I use an older version of MBE (from vim.org) FuzzyFinder also works fine (i.e. opens the file in the current window). So it seems that some interaction between FuzzyFinder and MBE 6.4.0 (also 6.4.1b1) is causing this odd behaviour.

**Comment by andrew-hill** [comment]
Okay I've just gone through and tested each committed version of the code.

Version 6.3.4 (from http://www.vim.org/scripts/script.php?script_id=3239) worked fine.

Version 6.3.5 (from the 6.3.7 tree in this git repo) causes FuzzyFinder to open a new split window about 2/3 the height of the MacVim tab (larger than the single line windows that 6.4 is producing).

This behaviour persists until commit a07f8ac8c38daade6158 described as "Update to 6.4.0" where the new window is reduced to a single line (instead of 2/3 of the screen).

So the behaviour changes appear to be
1) the first commit compared to the older 6.3.4 code (opens a new window instead of using the current one)
2) commit a07f8ac8c38daade6158 where the version number is set to 6.4.0 in the code itself, and the new window is now only one line high.

**Comment by fholgado** [comment]
Hi drfrogsplat,

Thanks for your awesome report! I am looking into this to see what could have caused the issue. I don't recall having changed the mechanism that opens the buffers, so it might be something else affecting this issue. I'll keep you posted on what I find.

Thanks again!

**Comment by andrew-hill** [comment]
I think I've found another way to trigger the weird 1-row-high new window bug.

I'm pretty sure it's related to the buffer(s) that FuzzyFinder uses to bring up its menu system, because if I do the following, I get the same bug:
1. Open up a FuzzyFinder menu
2. Don't actually type anything, just hit ESC to make it go away
3. type :e filename to open a file

This suggests that it's actually the buffer that FuzzyFinder creates that is being reused for some reason... only happens with newer versions of MBE running though.

**Comment by fholgado** [comment]
drfrogsplat,

I will tackle this issue as soon as I am done with the others. The other stuff is related to code that I've added to MBE so I am much more familiar with it. This seems to be an underlying issue from the plugin which I'll have to fix. I am exited to learn about this stuff though, so I will get to it as soon as I can. Thanks for your patience!

**Comment by andrew-hill** [comment]
So from my earlier comment, the issue first showed up between 6.3.4 and 6.3.5, which was your first change/release (Friday December 11, 2010 from the "Last Change" field in the header of the mbe plugin file).

After diffing the two files I've noticed the following changes, (ignoring the logs/help):
1. adding a third argument to several functions to specify a buffer name (often passed in as 'bufname("%")' or passed through functions)
2. a new function MBEMarkCurrent() + key mapping to it
3. some additional syntax matching + highlights for "Active" buffers

it seems like the first two are related, but my guess is it's related to the first change...?

**Comment by andrew-hill** [comment]
Also interesting is that I've figured out another way to cause it that I'm pretty sure is unrelated to other plugins:
1. make sure ctrl+tab to change buffers is enabled via:
   
   <pre><code>let g:miniBufExplMapCTabSwitchBufs = 1</code></pre>
2. open two files (i'll call them _fileA_ and _fileB_) at once so that you have the MBE window at the top (or bottom depending on your settings) and file A visible
3. press <leader>mbe (or whatever your shortcut to open and move the cursor to the MBE window is) — the cursor will move up to the MBE window, over file A's title with A marked "_MBEVisibleNormalActive_" and B marked "_MBENormal_":
   
    <pre><code>[1:fileA]*![3:fileB]</code></pre>
4. press that shortcut _again_ while the cursor is in the MBE window — now fileA becomes "_MBEVisibleNormal_" (the '!' will disappear from the MBE window, and depending on your highlighting the colour may change):
   
   <pre><code>[1:fileA]*[3:fileB]</code></pre>
5. now press Ctrl+Tab to switch buffers — instead of switching between fileA and fileB in the buffer shown below as would normally occur, a new split window is opened up, 1 row high, with fileB in it, which is now marked "_MBEVisibleNormalActive_" while fileA remains in the larger, lower window and remains marked "_MBEVisibleNormal_":
   
   <pre><code>[1:fileA]*[3:fileB]*!</code></pre>

This also causes some strange behaviour in the highlighting within the MBE window, where two characters are highlighted by their position in the MBE window, based on their column/position. Clicking on a buffer name in the MBE window using the mouse seems to fix this glitch though.

My settings from .vimrc are:

```
map <Leader>b :MiniBufExplorer<cr>
map <Leader>B :UMiniBufExplorer<cr>
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplUseSingleClick = 1
let g:miniBufExplSplitBelow = 0
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplMapCHLSwitchBufs = 1
let g:miniBufExplorerMoreThanOne = 1
let g:miniBufExplSplitToEdge = 1
```

removing all these doesn't fix the problem with FuzzyFinder, and for whatever reason the MapCTab setting is required to reproduce the same bug _without_ FuzzyFinder.

**Comment by andrew-hill** [comment]
Okay it looks like step 4 wasn't actually required (so is either a different, and not very concerning bug or is maybe related to the marking/listing of buffers?).

Just pressing Ctrl+Tab while the MBE window is active seems to trigger the bug.

And there's a slight difference in behaviour if your .vimrc doesn't include:

<pre><code>let g:miniBufExplSplitBelow = 0</code></pre>

In that case, the 1 row high window and the MBE window both appear down the _bottom_ instead of the top, but otherwise behaves as described.

**Comment by fholgado** [comment]
drfrogsplat,

You are awesome! Thanks so much for the detailed reports. I think this makes it a lot easier in terms of finding out what's wrong. I will take a look at 6.3.4 and figure out what else might have caused this to happen. I should be able to look at it this weekend.

Thanks again, and I'll keep you updated!

**Comment by toupeira** [comment]
I also stumbled over this bug and narrowed it down to the `AutoUpdate` function, if I add an exception to skip FuzzyFinder's buffer everything seems to work fine:

```
diff --git a/plugin/minibufexpl.vim b/plugin/minibufexpl.vim
index 18c6a82..d77047c 100644
--- a/plugin/minibufexpl.vim
+++ b/plugin/minibufexpl.vim
@@ -1390,7 +1393,7 @@ function! <SID>AutoUpdate(delBufNum,currBufName)
   endif

   " Don't bother autoupdating the MBE window
-  if (bufname('%') == '-MiniBufExplorer-')
+  if (bufname('%') == '-MiniBufExplorer-' || bufname('%') == '[fuf]')
     " If this is the only buffer left then toggle the buffer
     if (winbufnr(2) == -1)
         call <SID>CycleBuffer(1)
```

**Comment by fholgado** [comment]
Hi toupeira. Thanks so much for that patch! I've just merged it into the current development branch so that everyone else can test it out. drfrogsplat, could you check this out as well?

Here's the link: https://github.com/fholgado/minibufexpl.vim/tree/6.4.1b4

As always, keep me posted on the details. Thanks again!

**Comment by toupeira** [comment]
So TIL how to track a remote branch with Git ;-)

FuzzyFinder still works fine, but now I've stumbled over the following problem:

When you're on the first of multiple buffers but only have one window open (not counting MBE) and press :q or <C-W>c, MBE is closed instead of the window. In the master branch it reappears immediately.

**Comment by toupeira** [comment]
An apparently related problem is that the first buffer has the MBEVisibleNormal highlighting instead of MBEVisibleActive.

Oh and by the way, in the help at the top of minibufexpl.vim it says MBEVisibleNormalActive instead of MBEVisibleActive ;-)

Let me know if I should turn on any debug flags.

**Comment by andrew-hill** [comment]
sorry, just realised I hadn't commented on this (attempted to do so from my phone's browser which apparently didn't work!) — anyway, have been using the updated version for several days and have only had one or two cases of strange splits happening, in general everything is fixed and I'm able to use FuzzyFinder normally (:

I guess there's a question regarding this patch as to whether there's a better condition to test than checking for specific buffer names of MBE or fuf... i can imagine that there's a bunch of other plugins out there with buffers that could be added to this list, so just wondering if there's some property or characteristic of buffers that might allow exclusion here...?

**Comment by fholgado** [comment]
Hi Dr. Frog,

I totally agree. I merged it in the code with a note that this is temporary for now. I think this issue is related to [https://github.com/fholgado/minibufexpl.vim/issues/7](Issue #6).

I am almost done with school, and I'm planning to start from the original MBE version that does not exhibit these issues to figure out what changes cause this to happen. Thanks for your patience, we'll get it working properly soon!

**Comment by ivanov** [comment]
I just wanted to add that something similar was originally reported as a bug against ivanov/vim-ipython#7 - and there I said that one workaround is to `:let g:miniBufExplorerAutoUpdate=0` because otherwise, `ctrl-w p` is broken - any time you switch from one vim window to another - you can't go back to the first using `ctrl-w p` because that will always take you back to minibuf

**Comment by folke** [comment]
I seem to be having this issue with the latest version of MBE

**Comment by fholgado** [comment]
If you guys can confirm this is fixed, I'll close this one :)

**Comment by toupeira** [comment]
I haven't had any problems with FuzzyFinder for a while now.

**Comment by andrew-hill** [comment]
yeah haven't noticed any issues with FuzzyFinder for a while either, so i guess its all ok

**Comment by weynhamz** [comment]
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

The real issue is not about the empty buffer name, I think it is mainly because MBE steal the focus for a little bit while entering a buffer, after returning to the buffer, the 'wincmd p' would be pointed to MBE window. I believe that techlivezheng/vim-plugin-minibufexpl@3add236 and techlivezheng/vim-plugin-minibufexpl@4155048 should fix this issue now. 

Please give it a try and let me know if it works.

**Comment by weynhamz** [comment]
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.
