### ISSUE TITLE
Invalid range errors when used with LustyExplorer

### ISSUE THREAD

**Issue by mikehaertl** [fholgado/minibufexpl.vim#33]
I use the [LustyExplorer](http://www.vim.org/scripts/script.php?script_id=1890) extension and often, when i open it, i see errors like these popping up from minibufexplorer:

```
Error detected while processing function <SNR>22_AutoUpdate..<SNR>22_StartExplorer:
line 127:
E16: Invalid range
```

**Comment by weynhamz** [comment]
Hey, I am closing this issue, because it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5.
