### ISSUE TITLE
Project seems to be dead

### ISSUE THREAD

**Issue by mikehaertl** [fholgado/minibufexpl.vim#38]
Unfortunately it seems like @fholgado has lost interest in this project. There has been no updates for months now and no issues are adressed anymore.

This is a petty as i really like the improved version - but there are some open issues.

I found no better way than to open a ticket for this, as this may catch some attention from other developers. Is anyone willing to take over maintenance? Is there a fork which could replace this repo here?

**Comment by fholgado** [comment]
Hi guys,  

I am so sorry for the delays. Just moved + new job + life in general has gotten in the way a bit. I am still interested in keeping up with MBE, and I should have some time this weekend to take a look at the pull requests and fix a few issues.

I'll keep you posted!  

## 

Federico

**Comment by mikehaertl** [comment]
Hi Federico,

thanks a lot for the update. This gives me new hope.

Wish you all the best and sorry for the agitating. ;)
