### ISSUE TITLE
Color settings for the MBE window have no effect in the shell

### ISSUE THREAD

**Issue by davidhalter** [fholgado/minibufexpl.vim#39]
Hi!

I'm currently using the gnome-terminal to do most of my work, including all the vim stuff.
I wanted to change the colors of the MBE window (in my .vimrc):
hi MBENormal ctermfg=cyan

which has no effect, but:
:verbose hi MBENormal
MBENormal      xxx cterm=bold ctermfg=6
        Last set from ~/.vimrc

I also tried installing gvim (GTK) to test if it would work in a gui version. But it didn't. I also looked into the code and don't quite understand what the syntax declarations are doing. Besides i didn't find any other color specific settings, than the MBE\* highlighting definitions.

So do you know, what I have to do, that highlighting works?

Thank you!
David

**Comment by av930** [comment]
I have same problem, No color changed? is there specific setting for color effect in vimrc ?

**Comment by av930** [comment]
I solved this problem using inkpot color scheme with this conf.
"let g:inkpot_black_background = 1 "disable this line..

**Comment by cammacrae** [comment]
I have the same issue - setting highlight colors has no effect. Using tmux and 256 color xterm.

**Comment by weynhamz** [comment]
Hey, try set 'g:did_minibufexplorer_syntax_inits'  to 1.
