### ISSUE TITLE
Option to hide statusline (Toggle)

### ISSUE THREAD

**Issue by tutorgit** [fholgado/minibufexpl.vim#40]
This would be nice feature, as generally I  don't need the statusline.

**Comment by nixmaniack** [comment]
I also want to disable the statusline. Is there any way right now? If not would be a good feature.

**Comment by fholgado** [comment]
The only thing you can do is remove the text of the statusline. Since MBE is actually a buffer, it HAS to have a statusline. I'd remove it too if I could ;)
