### ISSUE TITLE
:q sometimes closes MBE instead of current buffer

### ISSUE THREAD

**Issue by toupeira** [fholgado/minibufexpl.vim#41]
If I run Vim and pass at least 2 file arguments, and then press `:q` in the first buffer, MBE gets closed instead of the file. If I switch to another buffer, `:q` correctly closes that file instead of MBE. If I switch to another buffer and then back to the first one, `:q` again closes MBE instead of the file.

This bug seems to be present in the vim.org version too, but for some reason I've never noticed it before.

**Comment by av930** [comment]
please refer below issue
https://github.com/fholgado/minibufexpl.vim/issues/1
