### ISSUE TITLE
ack.vim splits minibufexpl window

### ISSUE THREAD

**Issue by stephenmckinney** [fholgado/minibufexpl.vim#42]
To reproduce:
Do a search with ack.vim: `Ack! foo`
Go to a file in the list list and hit the `v` key
The file is opened in a tiny tiny split window next to minibufexpl

The cause:
The `v` key in ack.vim uses the following `exec "nnoremap <silent> <buffer> v <C-W><C-W><C-W>v<C-L><C-W><C-J><CR>"` at https://github.com/mileszs/ack.vim/blob/master/plugin/ack.vim#L56. It goes to the top window available, splits it, and opens the selected file in that window.

I realize that key isn't mapped in minibufexpl but ack.vim is a very popular plugin. Is there a way to prevent minibufexpl from being split?

**Comment by weynhamz** [comment]
I think it is the ACK should be fixed, the commands bunded to key `v` is not a good way of opening a file in a split. Also, these commands might have a chance to trigger MBE's auto-updating which would have a risk to break the window history and only make things worse. This is not a MBE issue, better to refactor ACK to find a way to open the file in an appropriate window.
