### ISSUE TITLE
Conflict with Fugitive Gdiff

### ISSUE THREAD

**Issue by maciakl** [fholgado/minibufexpl.vim#48]
I use MiniBuffExpl along side of the Fugitive plugin and I noticed that when I run :Gdiff it correctly opens two files side by side, but then diffs one of them with the MiniBuffExpl buffer. Is there a way to prevent this? I'm filing bug reports here and for fugitive to see if one of the projects can get it fixed. 

Could there be a way to temporarily suppress MBE for certain calls? My workaround right now is this:

```
let g:miniBufExplorerMoreThanOne=3
```

This way MBE does not trigger when I do Gdiff.

**Comment by blob42** [comment]
+1

 same issue here, looking for a way to pause MBE while using fugitive :/

**Comment by brookhong** [comment]
+1

**Comment by weynhamz** [comment]
Related to #3

**Comment by weynhamz** [comment]
Related to #17
