### ISSUE TITLE
Cannot switch between buffers when set show buf numbers = 0

### ISSUE THREAD

**Issue by ditsing** [fholgado/minibufexpl.vim#49]
After adding

``` vim
let g:miniBufExplShowBufNumbers = 0
```

to my vimrc file, I cann't switch between buffers by hitting enter on the tab of mbe.

Vim keeps saying:

> Error detected while processing function <SNR>23_MBESelectBuffer:
> Zero count: b! 0

I believe that the function `GetSelectedBuffer` returns a wrong value.
`GetSelectedBuffer` gets the count number by `subtitute`.

**Comment by polmiro** [comment]
I noticed the same issue. No big deal but the option to remove the numbers becomes quite useless.

**Comment by weynhamz** [comment]
Fixed in develop branch, closing this issue, feel free to reopen if it still bites.
