### ISSUE TITLE
Feature: Shortcuts for buffers based on position in MBE (not buffer number)

### ISSUE THREAD

**Issue by andrew-hill** [fholgado/minibufexpl.vim#52]
Looking at an editor like TextMate (and plenty of others) you can switch between files using something like cmd+1,2,3,4,etc, as well as rearrange the open "tabs" to let you switch between documents easily.

Would be useful if there was a way to access the buffers listed in MBE based on their ordering in MBE (rather than simply buffer numbers via :b# as is currently available). This would allow similar direct access to buffers (regardless of how many buffers you've opened/closed) with a common set of shortcuts.

I had a look around for alternative ways, and apparently its not possible to re-use buffers, so it seems to make sense to make this part of MBE which is displaying a tab-like set of buffer names already...?

**Comment by weynhamz** [comment]
Related #26, please refer to that one insead.
