### ISSUE TITLE
MBE comflict with BuffExplorer ?

### ISSUE THREAD

**Issue by fwolf** [fholgado/minibufexpl.vim#68]
Original installed BuffExplored and worked well,
After install MBE,
I can't open buffer list using '\be' key,
but '\bv' works.

Is there any conflict or keymap duplicate ?

My vimrc:
https://github.com/fwolf/fwolfrc/blob/1e7a826ce71fe5509e6b84d22c273f5cb31458f8/vimrc

BuffExplorer version: 7.3.0
Vim: 7.3

**Comment by fwolf** [comment]
Add:

Seems this happen when I have this line in vimrc:

```
map <silent> <F7> :TMiniBufExplorer<CR>
```

Remove this line then '\be' are useable.

Why ??

**Comment by weynhamz** [comment]
@fwolf `map <silent> <F7> :TMiniBufExplorer<CR>` 应该不是造成 `\be` 失效的原因，MBE 也没有绑定 `be` 开头的键，所以应该是其它的原因造成的。

貌似你使用的是 scripts.vim.org 上的 MBE，已经比较旧了，试试这个仓库的版本吧，或者[我的 develop 分支](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop)（有大量的改进和重构，不过默认的键绑定已经全部移除了，这应该是用户自己的事），或者等新的版本 6.5 （就快在 @fholgado 的仓库发布了）。

我先把这个问题关闭了，如果还有问题，欢迎重新打开。

**Comment by fwolf** [comment]
ok, 我现在已经用上 @fholgado 的版本了，并且不再使用 BuffExplorer。

`\be` 失效的原因，大概是与 BuffExplorer 函数重名导致的，我换用 SelectBuf 就没事了。
