### ISSUE TITLE
setting shellslash on win breaks shellescape

### ISSUE THREAD

**Issue by dezza** [fholgado/minibufexpl.vim#70]
```
  if (has("win32") || has("win64"))
      ""set shellslash
  endif
```

Breaks other plugins like Syntastic ...

Setting shellslash on Windows is not good, since it prevents shellescape (built-in function) to work as expected.

**Comment by weynhamz** [comment]
Please take a look at [the develop branch of techlivezheng/vim-plugin-minibufexpl](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop), it has been fixed there, and the development of this plugin is also there too.

**Comment by dezza** [comment]
OK, I should simply start pulling from this rep?

**Comment by weynhamz** [comment]
@dezza Yes, you could use that branch at the present. A new version will be released to this repo soon, you can change back if you like.

**Comment by weynhamz** [comment]
Duplicate of #51
