### ISSUE TITLE
Change behavior to select the new active buffer after deleting

### ISSUE THREAD

**Issue by jeremymarc** [fholgado/minibufexpl.vim#72]
What's the current behavior to select the new active buffer after deleting one ? I don't understand how it's working. I would like to select the previous opened one.

**Comment by weynhamz** [comment]
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by weynhamz** [comment]
Use 'MBEbd' command introduced in develop branch, should do want you desired.

Closing this issue, feel free to reopen it.
