### ISSUE TITLE
Not working with vimwiki on windows systems

### ISSUE THREAD

**Issue by mmbradle** [fholgado/minibufexpl.vim#74]
minibufexpl sets shellslash on windows systems. 

minibufexpl.vim (line 468)

```
" Set shellslash for Windows/DOS Vim for dupeBufName checking to Work
  if (has("win32") || has("win64"))
      set shellslash
  endif
```

This seems to cause shellescape() to output shell commands surrounded by single quotes. I believe windows cannot handle paths surrounded by single quotes and thus things start breaking because shell commands stop working.

Running a command in windows cmd surrounded by single quotes yields the following:

```
c:\>dir 'c:\windows'
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by mmbradle** [comment]
looks like a duplicate of this:
https://github.com/fholgado/minibufexpl.vim/issues/51

I'm running 6.4.4 and that issue states that 6.5 is supposed to fix this issue.

**Comment by weynhamz** [comment]
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by weynhamz** [comment]
Closing this issue, it should be fixed in the develop branch, feel free to reopen it.
