### ISSUE TITLE
NERDTreeToggle cycle moves cursor to MiniBuffExpl

### ISSUE THREAD

**Issue by swinman** [fholgado/minibufexpl.vim#75]
When NerdTree is toggled on, the cursor moves to the NERD tree - then when it is toggled off the active pane / window gets switched to the minibuf - but it should have gone back to the active buffer / pane that NERD tree was called from.

same thing happens with Tlist close

there is also an issue using the <C-^> command because for some reason minibuf was the most recent active buffer - even though it was never the active buffer.

**Comment by weynhamz** [comment]
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by weynhamz** [comment]
Related to #3

**Comment by weynhamz** [comment]
Closing this issue, it should be fixed in the develop branch, feel free to reopen it.
