### ISSUE TITLE
slow if too many buffers are open

### ISSUE THREAD

**Issue by yshavit** [fholgado/minibufexpl.vim#77]
MBE seems to degrade in performance fairly quickly. With just a few files open, it works fine. But even ten files produces a noticeable delay, and 20 is slow enough that I wouldn't want to use it.

The files I'm using are trivially small:

```
mkdir /tmp/lotsafiles
cd /tmp/lotsafiles
for i in {1..20}; do touch "$i.txt"; done
vim *.txt
```

**Comment by mvgrimes** [comment]
You can speed it up by setting a flag in you .vimrc file:

   let g:miniBufExplCheckDupeBufs = 0

An explanation can be found in the source of minibufexpl.vim.

**Comment by yshavit** [comment]
Perfect, thanks!

**Comment by weynhamz** [comment]
Related to #5

**Comment by weynhamz** [comment]
Duplicate of #6

**Comment by weynhamz** [comment]
Better to try the develop branch, should be fixed there.
