### ISSUE TITLE
There is some extra buffers when I close all the window

### ISSUE THREAD

**Issue by ysyshtc** [fholgado/minibufexpl.vim#78]
When I close all the windows using :q, some extra buffers occur with syntax highlight. Is it a bug?

**Comment by weynhamz** [comment]
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by ysyshtc** [comment]
Excellent! You did a good job, it seems work out! Thank you :)

**Comment by weynhamz** [comment]
不客气:)

**Comment by weynhamz** [comment]
Duplicate of #1
