### ISSUE TITLE
Problem with a new tab

### ISSUE THREAD

**Issue by szw** [fholgado/minibufexpl.vim#79]
On new tab (:tabe or :tabnew) the first buffer is loaded automatically instead of the newly created one.
As a temporary workaround I use <F11> mapping to open new tabs:
noremap <silent><F11> :tabe<CR>:UMiniBufExplorer<CR>:blast<CR>

Another notice here: 
I think MiniBufExpl should show unnamed buffers. Currently it omits them and this is very bad. There should right and simple way to get back to the unnamed buffer. Especially, if one's using ":hidden" option.

**Comment by weynhamz** [comment]
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by weynhamz** [comment]
Closing this issue, it should be fixed in the develop branch by commit c06f82d, feel free to reopen it.

**Comment by weynhamz** [comment]
Related #47
