### ISSUE TITLE
Make duplicate name detection optional

### ISSUE THREAD

**Issue by toupeira** [fholgado/minibufexpl.vim#8]
I get a noticable delay when opening multiple files from the command-line, which goes away if I comment out the duplicate name detection and replace it with the original buffer title code from the old MiniBufExpl.

Could you make this feature optional?

**Comment by fholgado** [comment]
Hey man,

I can look into making it optional. I am a couple of weeks from finishing school and am planning on rewriting how this is implemented so that it can be more efficient. I'll keep this open for now to remind me to take a look when I start working on MBE again.

Thanks!

**Comment by toupeira** [comment]
Thanks, and take your time ;-)

**Comment by fholgado** [comment]
Thanks for your patience :)

**Comment by fholgado** [comment]
This has been added in the latest development release. Can you please test it to make sure it works properly?

https://github.com/fholgado/minibufexpl.vim/blob/development/plugin/minibufexpl.vim

Thanks!

**Comment by toupeira** [comment]
Thank you! I tested it and it does indeed work properly :)
