### ISSUE TITLE
When i toggle minibufexplorer,  it will resize window when nerdtree is open.

### ISSUE THREAD

**Issue by lsaint** [fholgado/minibufexpl.vim#80]
http://stackoverflow.com/questions/11409671/when-i-toggle-minibufexplorer-how-to-stop-resizing-window-when-nerdtree-is-open

Please see the question on Stackoverflow. thx.

**Comment by weynhamz** [comment]
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by lsaint** [comment]
还是一样的，看看我的步骤有没问题。

```
git clone git://github.com/techlivezheng/vim-plugin-minibufexpl.git
git checkout --track origin/develop
git pull
```

2013/5/8 Techlive Zheng notifications@github.com

**Comment by weynhamz** [comment]
这确实是个 bug，已确认。

**Comment by lsaint** [comment]
好的，谢谢答复。

2013/5/8 Techlive Zheng notifications@github.com

**Comment by weynhamz** [comment]
已在 develop 分支修复，请确认。

**Comment by lsaint** [comment]
确认修复，thx:)

2013/5/9 Techlive Zheng notifications@github.com
