### ISSUE TITLE
Loses "sync" with opened buffers

### ISSUE THREAD

**Issue by mustafa0x** [fholgado/minibufexpl.vim#82]
MiniBufExpl regularly loses sync with the opened buffers -- the explorer is no longer updated when a buffer is added or removed, and the highlighted buffer gets stuck on one of the buffers.

![Screenshot-1](https://f.cloud.github.com/assets/1473102/406486/1c13858a-aa96-11e2-9a5a-e20aa5e74984.png)

When this occurs, and I `:bd`, I get this:

![Screenshot](https://f.cloud.github.com/assets/1473102/406482/fc8d79c8-aa95-11e2-98be-8e674dc39800.png)

This occurred on Linux and Windows. My .vimrc is relatively plain.

I haven't been able to specify exactly when this occurs, but at some point while working, it does (~2/hour).

**Comment by weynhamz** [comment]
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by weynhamz** [comment]
Closing this issue, it should be fixed in the develop branch, feel free to reopen it.
