### ISSUE TITLE
Freeze when used in conjunction with gmarik/vundle :BundleInstall command

### ISSUE THREAD

**Issue by DieterDePaepe** [fholgado/minibufexpl.vim#85]
Steps to reproduce:
- Install Vundle as plugin manager
- Setup Vundle to download this plugin - add the following to .vimrc: Bundle 'fholgado/minibufexpl.vim'
- Start vim (or gvim)
- Execute ":BundleInstall" to download the plugin (or do nothing when it's already installed)
- Execute ":q" to exit the Vundle buffer
- Vim is now frozen

This only occurs when there is nothing in your current buffer before you execute the ":BundleInstall", so if you type anything in the buffer first, or open an existing file, everything will be ok.

This bug no longer occurs on "techlivezheng/vim-plugin-minibufexpl".

This is my Vim build (I'm working on a 64b Win7 machine):
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 20 2013 13:28:35)
MS-Windows 32-bit console version
Included patches: 1-829

**Comment by weynhamz** [comment]
Thy the develop branch please. 

It seems you are using Vundle, then try the master of my fork.

**Comment by weynhamz** [comment]
Oh, it seems you have tried my master, I should have mentioned that, I am maintaining this project now, the develop branch of this repo is actually my master.

**Comment by weynhamz** [comment]
A new version will be released soon, it will be fixed then.

Closed.
