### ISSUE TITLE
gvim flashes when I set g:miniBufExplForceSyntaxEnable

### ISSUE THREAD

**Issue by zhoulike** [fholgado/minibufexpl.vim#86]
I use gvim 7.3 in win 8, and the setting of minibufexpl is : 
let g:miniBufExplForceSyntaxEnable = 1

This setting removes the bug of syntax highlighting. However, the interface of gvim flashes in this case. If I remove this line in _vimrc, everything is OK.

I always work and study in Ubuntu, and this setting is fine in Ubuntu.

**Comment by weynhamz** [comment]
Should be fixed in develop branch, please give it a shot.

**Comment by weynhamz** [comment]
Closing this, feel free to reopen it.

**Comment by zhoulike** [comment]
I just tested the develop branch. When I open many files, and type :q or :bd, it closes all buffers.

**Comment by weynhamz** [comment]
MBE should have handled this correctly, maybe its other plugin you installed that interfere the quiting process, you can try that by just load MBE.
