### ISSUE TITLE
':wq' doesn't exist vim

### ISSUE THREAD

**Issue by linhmtran168** [fholgado/minibufexpl.vim#89]
With the latest minibufexpl.vim, `:wq` doesn't exist vim but leaves a big minibufexpl.vim open. I must type `:q` another time to be able to quit vim.

![screen shot 2013-06-18 at 12 59 57 pm](https://f.cloud.github.com/assets/646436/666883/59636a68-d7dc-11e2-8d16-02cc2ba4820c.png)

**Comment by weynhamz** [comment]
This shouldn't be, which version of Vim are you using? Could you test it by just enable MBE to see if it really the MBE's problem?

**Comment by linhmtran168** [comment]
I'm using MacVim 7.3-66. This is the output from `:version` command

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Dec 12 2012 16:22:25)
MacOS X (unix) version
Included patches: 1-754
```

I did disable all other plugins but the problem still appeared.
You can take a look at my .vimrc here https://github.com/linhmtran168/mac_dotfiles/blob/master/.vimrc

**Comment by weynhamz** [comment]
MBE is currently using 'QuitPre' event to close itself before the quitting, there seems a bug that ['QuitPre' wouldn't be called befroe ':wq'](https://groups.google.com/forum/?fromgroups#!topic/vim_dev/f85fzX93CZU), you might need to upgrade your Vim to a newer version, I am using 7.3.918 which is working properly.

**Comment by linhmtran168** [comment]
@techlivezheng Thank you, updated to the master branch of macvim and the problem was fixed

**Comment by weynhamz** [comment]
@linhmtran168 You are welcome, glad to see it helps.

**Comment by sumonto** [comment]
Please give me a link on how to update to latest patch fix, 
I had downloaded the latest win installer 2 days back from vim.org.

thanks.

**Comment by weynhamz** [comment]
@sumonto If the win installer vim.org provides is not new enough, you might need to build it yourself. As for how to build Vim on M$ Windows, sorry I really can't help you, you are on your own I am afraid.

**Comment by sumonto** [comment]
> hg summary
> parent: 2572:ee53a39d5896
>  Last changes for the 7.3 release!
> branch: vim73
> commit: 2 modified, 1875 unknown
> update: (current)

(2 modified files are make files to build using VS 2012)
I was finally able to build on windows using Visual Studios 2012 Compiler
Scenario 1: (0 buffers or 1 buffer open)
:bd closes the single buffer, but does not close GVim.exe

Scenario 2: (2 or more buffers open)
:bd closes GVim.exe

Thanks for your help so far.
Sumonto
