### ISSUE TITLE
MiniBufExplorer window resizes when using ZoomWin

### ISSUE THREAD

**Issue by saamalik** [fholgado/minibufexpl.vim#91]
Hi,
I don't know if this is a MiniBufExplorer problem or ZoomWin--but I thought I'd post here first. 

The MiniBufExplorer resizes and takes half-the horizontal space after a ZoomWin sequence (`<C-W>o`) on restore.
1. Open two files--2 buffers. MBE opens up.
2. Zoom into the main window: `<C-w>o`. 
3. Zoom out: `<C-w>o`
4. Switch to the next buffer: `:bn`
5. Notice that MBE now takes up half the vertical space. 

![mbe_vertically_expands](https://f.cloud.github.com/assets/1455661/717821/adefbd6e-df54-11e2-8bfc-b615e9e2a7b2.png)

**Comment by weynhamz** [comment]
What's your MBE's version?

**Comment by saamalik** [comment]
Still reproducible in the latest commit: 349a9fbb7a9da13d029b6a7ed8c8a5e9c048c4ec

**Comment by weynhamz** [comment]
Yeah, I just test it, it seems ZoomWin does not restore 'winfixheight' and 'winfixwidth' option after retore the windows. You need to file a bug report toZoomWin to make it keep the 'winfixheight' and 'winfixwidth' settings across the zooming.

**Comment by weynhamz** [comment]
You can either contact the author to add `wfh` and `wfw` to `s:localoptlist`, or just set `g:zoomwin_localoptlist` option to the orignal value of `s:localoptlist` plus `wfh` and `wfw` like the following if you are using 25g ASTRO-ONLY from the author's site.

```
let g:zoomwin_localoptlist   = ["ai","ar","bh","bin","bl","bomb","bt","cfu","ci","cin","cink","cino","cinw","cms","com","cpt","diff","efm","eol","ep","et","fenc","fex","ff","flp","fo","ft","gp","imi","ims","inde","inex","indk","inf","isk","key","kmp","lisp","mps","ml","ma","mod","nf","ofu","oft","pi","qe","ro","sw","sn","si","sts","spc","spf","spl","sua","swf","smc","syn","ts","tx","tw","udf","wm", "wfh", "wfw"]
```

**Comment by saamalik** [comment]
ok thanks!
