### ISSUE TITLE
Error when opening session files

### ISSUE THREAD

**Issue by af** [fholgado/minibufexpl.vim#94]
Hi,
I'm getting an error every time I restore from a session file that I saved while using MiniBufExplorer.

I'm saving the session with `:mksession .testsesh`, then closing vim and running `:so .testsesh`.

![screen shot 2013-07-05 at 1 43 47 pm](https://f.cloud.github.com/assets/25241/755524/ebb0032e-e5b3-11e2-8718-7dbf6f586491.png)

The line in question (in the session file) reads:

```
file -MiniBufExplorer-
```

And after opening the session, all of the files are there as expected, but it looks like there are a couple extra windows at the bottom below the statusline... this could just be a vim-powerline thing though:

![screen shot 2013-07-05 at 1 52 56 pm](https://f.cloud.github.com/assets/25241/755555/5ae63a46-e5b5-11e2-8937-7b506e08c2d7.png)

Got the same result in both MacVim and Vim 7.3.

**Comment by weynhamz** [comment]
Are you at the master of this repo? Did you try the develop branch?

**Comment by af** [comment]
Hi,
Yes, this was on master, at commit ad72976ca3df4585d49aa296799f14f3b34cf953.

I just tried the develop branch and got the same result. Let me know if there's anything else you want me to try!

**Comment by af** [comment]
Just realized this was still open– nobody else seems to have the issue and I'm using a different plugin now, so will close.
